### ISSUE TITLE
'trigger' property as an array

### ISSUE THREAD

**Issue by theohdv** [harshq/react-native-mentions#21]
I was looking for a component to manage mention suggestion in my app and I found yours. The only problem is that I also need in the same input a hashtag suggestion.

I can't do it with your component because the prop `trigger` only accepts a string.

Do you think we could change this to also accept an array of string (['@', '#'] for my case)?

If you think it could be added to your component but you don't have time to implement it just tell me and I will create a PR for that.

Good job for the component!

**Comment by theohdv** [comment]
Duplicate of #12

**Comment by rupalpatel0008** [comment]
@theohdv Have to work on this?
