### ISSUE TITLE
Show suggestions even after selecting one and editing the @mention

### ISSUE THREAD

**Issue by gianpaj** [harshq/react-native-mentions#27]
This is what I mean.

1. On Instagram comments, type:
`@john`
2. Tap on any user suggestion
3. The result text comment will be:
`@john ` (notice the white space)
The suggestions UI will disappear.
4. Delete the whitespace and the suggestions appear again.

How would we add this feature?

**Comment by dabakovich** [comment]
You can try a `react-native-controlled-mentions` that is not rich in configuration yet but enough stable for use in projects.
https://www.npmjs.com/package/react-native-controlled-mentions

**Comment by dabakovich** [comment]
You can try a `react-native-controlled-mentions` that is not rich in configuration yet but enough stable for use in projects.
https://www.npmjs.com/package/react-native-controlled-mentions
