### ISSUE TITLE
Customize @mentions colors

### ISSUE THREAD

**Issue by alex-pouivet** [harshq/react-native-mentions#40]
Hi, is it possible to customize the background-color of the @mention, like Facebook for example ? And to delete the all @mention name in one click and not delete letter by letter like now ?

**Comment by mrazadar** [comment]
Hey just published a new [react-native-mentions](https://www.npmjs.com/package/react-native-mentions-editor) package. Check it out.

**Comment by 14BCS1464** [comment]
Here is the Solution plz try it



import React from 'react';
import { View, Text, TextInput, } from 'react-native';
export default class App extends React.Component {
    state = {
        caption: '',
    }

    returnColor=(val:any)=>{
        this.setState({
            caption:val
        })
    }
    render() {
        return (
            <View style={{ marginTop: 48 }}>
              <TextInput
                  onChangeText={(val)=>this.returnColor(val)}
                   style={{height:70,width:300}}>
                              <Text style={{color:'white'}}>
                                  {this.state.caption.split(" ").map((text, rowIndex) => {
                                      if (/^@/.test(text)) {
                                          return <Text key={text} style={{ fontSize: 18, color:'red' }}>{this.state.caption.split(" ").length == (rowIndex+1) ? text : text + " "}</Text>;
                                      } else {
                                          return this.state.caption.split(" ").length == (rowIndex+1) ? text : text + " ";
                                      }
                                  })}
                              </Text>
            </TextInput>
            </View>
        );
    }
}

**Comment by SreehariKunjunni** [comment]
Works perfectly fine.. Thanks bro.... u are a dinkan....
