### ISSUE TITLE
ListView Horizontal

### ISSUE THREAD

**Issue by joaovpmamede** [harshq/react-native-mentions#6]
Does it have to be horizontal by default?
I wish we could set it's orientation. Is this something you'd be willing to add/change?

Oh and thanks for the library.

**Comment by harshq** [comment]
Hey. Was bit busy with the work lately. I will give this a try over the weekend. Cheers!

**Comment by harshq** [comment]
orientation support is added with [this](https://github.com/harshq/react-native-mentions/commit/e6903db0d13bdef737efd69eedace7d636439edb).
